# .goreleaser.yml
# This is a Go library, not a binary application
# We skip builds and only create source archives
builds:
  - skip: true

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  version_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Release
release:
  github:
    owner: ZaguanLabs
    name: xai-sdk-go
  draft: false
  prerelease: auto
